package de.fraunhofer.isst.health.transit.utils.gpas.domain;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;

/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-17T10:42:08.796Z
 * Generated source version: 4.1.1
 */
@WebServiceClient(name = "DomainManagerBeanService",
        wsdlLocation = "http://gpas.develop-dmu.dmu.dev.num-rdp.de/gpas/DomainService?wsdl",
        targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/")
public class DomainManagerBeanService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://psn.ttp.ganimed.icmvc.emau.org/", "DomainManagerBeanService");
    public static final QName DOMAIN_SERVICE_PORT = new QName("http://psn.ttp.ganimed.icmvc.emau.org/", "DomainServicePort");

    static {
        URL url = null;
        try {
            url = URI.create("http://gpas.develop-dmu.dmu.dev.num-rdp.de/gpas/DomainService?wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DomainManagerBeanService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}",
                            "http://gpas.develop-dmu.dmu.dev.num-rdp.de/gpas/DomainService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DomainManagerBeanService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DomainManagerBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DomainManagerBeanService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DomainManagerBeanService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DomainManagerBeanService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DomainManagerBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }


    /**
     * @return returns DomainManager
     */
    @WebEndpoint(name = "DomainServicePort")
    public DomainManager getDomainServicePort() {
        return super.getPort(DOMAIN_SERVICE_PORT, DomainManager.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in
     *                 the <code>features</code> parameter will have their default values.
     * @return returns DomainManager
     */
    @WebEndpoint(name = "DomainServicePort")
    public DomainManager getDomainServicePort(WebServiceFeature... features) {
        return super.getPort(DOMAIN_SERVICE_PORT, DomainManager.class, features);
    }

}
