package de.fraunhofer.isst.health.transit.utils.gpas.domain;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-17T10:42:08.749Z
 * Generated source version: 4.1.1
 */
@WebService(targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/", name = "DomainManager")
@XmlSeeAlso({ObjectFactory.class})
public interface DomainManager {

    @WebMethod
    @RequestWrapper(localName = "deleteDomainWithPSNs", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.DeleteDomainWithPSNs")
    @ResponseWrapper(localName = "deleteDomainWithPSNsResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.DeleteDomainWithPSNsResponse")
    void deleteDomainWithPSNs(

            @WebParam(name = "domainName", targetNamespace = "") String domainName)
            throws UnknownDomainException, InvalidParameterExceptionException, DomainInUseException;

    @WebMethod
    @RequestWrapper(localName = "getDomainsForPrefix", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.GetDomainsForPrefix")
    @ResponseWrapper(localName = "getDomainsForPrefixResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.GetDomainsForPrefixResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.domain.GetDomainsForPrefixResponse.Return getDomainsForPrefix(

            @WebParam(name = "prefix", targetNamespace = "") String prefix) throws InvalidParameterExceptionException;

    @WebMethod
    @RequestWrapper(localName = "listPSNsPaginated", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.ListPSNsPaginated")
    @ResponseWrapper(localName = "listPSNsPaginatedResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.ListPSNsPaginatedResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.domain.ListPSNsPaginatedResponse.Return listPSNsPaginated(

            @WebParam(name = "domainName", targetNamespace = "") String domainName,
            @WebParam(name = "config", targetNamespace = "")
            de.fraunhofer.isst.health.transit.utils.gpas.domain.PaginationConfig config)
            throws UnknownDomainException, InvalidParameterExceptionException;

    @WebMethod
    @RequestWrapper(localName = "arePSNDeletable", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.ArePSNDeletable")
    @ResponseWrapper(localName = "arePSNDeletableResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.ArePSNDeletableResponse")
    @WebResult(name = "return", targetNamespace = "")
    boolean arePSNDeletable(

            @WebParam(name = "domainName", targetNamespace = "") String domainName)
            throws UnknownDomainException, InvalidParameterExceptionException;

    @WebMethod
    @RequestWrapper(localName = "getRestrictionForCheckDigitClass", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.GetRestrictionForCheckDigitClass")
    @ResponseWrapper(localName = "getRestrictionForCheckDigitClassResponse",
            targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.GetRestrictionForCheckDigitClassResponse")
    @WebResult(name = "alphabetRestriction", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.domain.GeneratorAlphabetRestriction getRestrictionForCheckDigitClass(

            @WebParam(name = "checkDigitClass", targetNamespace = "") String checkDigitClass)
            throws InvalidParameterExceptionException, InvalidCheckDigitClassException;

    @WebMethod
    @RequestWrapper(localName = "addDomain", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.AddDomain")
    @ResponseWrapper(localName = "addDomainResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.AddDomainResponse")
    void addDomain(

            @WebParam(name = "domainDTO", targetNamespace = "")
            de.fraunhofer.isst.health.transit.utils.gpas.domain.DomainInDTO domainDTO)
            throws InvalidParameterExceptionException, DomainInUseException, InvalidGeneratorException, InvalidAlphabetException,
            UnknownDomainException, InvalidParentDomainExceptionException, InvalidCheckDigitClassException;

    @WebMethod
    @RequestWrapper(localName = "getDomainsForSuffix", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.GetDomainsForSuffix")
    @ResponseWrapper(localName = "getDomainsForSuffixResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.GetDomainsForSuffixResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.domain.GetDomainsForSuffixResponse.Return getDomainsForSuffix(

            @WebParam(name = "suffix", targetNamespace = "") String suffix) throws InvalidParameterExceptionException;

    @WebMethod
    @RequestWrapper(localName = "listPSNs", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.ListPSNs")
    @ResponseWrapper(localName = "listPSNsResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.ListPSNsResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.domain.ListPSNsResponse.Return listPSNs(

            @WebParam(name = "domainName", targetNamespace = "") String domainName)
            throws UnknownDomainException, InvalidParameterExceptionException;

    @WebMethod
    @RequestWrapper(localName = "getDomain", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.GetDomain")
    @ResponseWrapper(localName = "getDomainResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.GetDomainResponse")
    @WebResult(name = "domain", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.domain.DomainOutDTO getDomain(

            @WebParam(name = "domainName", targetNamespace = "") String domainName)
            throws UnknownDomainException, InvalidParameterExceptionException;

    @WebMethod
    @RequestWrapper(localName = "countPSNsForDomains", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.CountPSNsForDomains")
    @ResponseWrapper(localName = "countPSNsForDomainsResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.CountPSNsForDomainsResponse")
    @WebResult(name = "psnCountForDomains", targetNamespace = "")
    long countPSNsForDomains(

            @WebParam(name = "domainNames", targetNamespace = "") java.util.List<String> domainNames,
            @WebParam(name = "config", targetNamespace = "")
            de.fraunhofer.isst.health.transit.utils.gpas.domain.PaginationConfig config)
            throws UnknownDomainException, InvalidParameterExceptionException;

    @WebMethod
    @RequestWrapper(localName = "listDomains", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.ListDomains")
    @ResponseWrapper(localName = "listDomainsResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.ListDomainsResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.domain.ListDomainsResponse.Return listDomains();

    @WebMethod
    @RequestWrapper(localName = "deleteDomain", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.DeleteDomain")
    @ResponseWrapper(localName = "deleteDomainResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.DeleteDomainResponse")
    void deleteDomain(

            @WebParam(name = "domainName", targetNamespace = "") String domainName)
            throws UnknownDomainException, InvalidParameterExceptionException, DomainInUseException;

    @WebMethod
    @RequestWrapper(localName = "updateDomain", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.UpdateDomain")
    @ResponseWrapper(localName = "updateDomainResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.UpdateDomainResponse")
    void updateDomain(

            @WebParam(name = "domainDTO", targetNamespace = "")
            de.fraunhofer.isst.health.transit.utils.gpas.domain.DomainInDTO domainDTO)
            throws InvalidParameterExceptionException, InvalidUpdateInUseOperationExceptionException, DomainInUseException,
            InvalidGeneratorException, InvalidAlphabetException, UnknownDomainException, InvalidParentDomainExceptionException,
            InvalidCheckDigitClassException;

    @WebMethod
    @RequestWrapper(localName = "countPSNs", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.CountPSNs")
    @ResponseWrapper(localName = "countPSNsResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.CountPSNsResponse")
    @WebResult(name = "psnCount", targetNamespace = "")
    long countPSNs(

            @WebParam(name = "domainName", targetNamespace = "") String domainName,
            @WebParam(name = "config", targetNamespace = "")
            de.fraunhofer.isst.health.transit.utils.gpas.domain.PaginationConfig config)
            throws UnknownDomainException, InvalidParameterExceptionException;

    @WebMethod
    @RequestWrapper(localName = "listPSNsForDomainsPaginated", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.ListPSNsForDomainsPaginated")
    @ResponseWrapper(localName = "listPSNsForDomainsPaginatedResponse",
            targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.ListPSNsForDomainsPaginatedResponse")
    @WebResult(name = "return", targetNamespace = "")
    ListPSNsForDomainsPaginatedResponse.Return listPSNsForDomainsPaginated(

            @WebParam(name = "domainNames", targetNamespace = "") java.util.List<String> domainNames,
            @WebParam(name = "config", targetNamespace = "")
            de.fraunhofer.isst.health.transit.utils.gpas.domain.PaginationConfig config)
            throws UnknownDomainException, InvalidParameterExceptionException;

    @WebMethod
    @RequestWrapper(localName = "getAlphabet", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.GetAlphabet")
    @ResponseWrapper(localName = "getAlphabetResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.GetAlphabetResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.domain.Alphabet getAlphabet(

            @WebParam(name = "alphabetName", targetNamespace = "") String alphabetName)
            throws InvalidAlphabetException, InvalidParameterExceptionException;

    @WebMethod
    @RequestWrapper(localName = "updateDomainInUse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.UpdateDomainInUse")
    @ResponseWrapper(localName = "updateDomainInUseResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.domain.UpdateDomainInUseResponse")
    void updateDomainInUse(

            @WebParam(name = "domainName", targetNamespace = "") String domainName,
            @WebParam(name = "label", targetNamespace = "") String label,
            @WebParam(name = "comment", targetNamespace = "") String comment,
            @WebParam(name = "parentDomainNames", targetNamespace = "") java.util.List<String> parentDomainNames,
            @WebParam(name = "sendNotificationsWeb", targetNamespace = "") boolean sendNotificationsWeb,
            @WebParam(name = "psnsDeletable", targetNamespace = "") boolean psnsDeletable)
            throws InvalidParameterExceptionException, InvalidUpdateInUseOperationExceptionException, InvalidGeneratorException,
            UnknownDomainException, InvalidAlphabetException, InvalidParentDomainExceptionException,
            InvalidCheckDigitClassException;
}
