
package de.fraunhofer.isst.health.transit.utils.gpas.domain;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-17T10:42:08.559Z
 * Generated source version: 4.1.1
 */

@WebFault(name = "DomainInUseException", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/")
public class DomainInUseException extends Exception {

    private de.fraunhofer.isst.health.transit.utils.gpas.domain.DomainInUseExceptionType faultInfo;

    public DomainInUseException() {
        super();
    }

    public DomainInUseException(String message) {
        super(message);
    }

    public DomainInUseException(String message, Throwable cause) {
        super(message, cause);
    }

    public DomainInUseException(String message,
                                DomainInUseExceptionType domainInUseException) {
        super(message);
        this.faultInfo = domainInUseException;
    }

    public DomainInUseException(String message,
                                DomainInUseExceptionType domainInUseException,
                                Throwable cause) {
        super(message, cause);
        this.faultInfo = domainInUseException;
    }

    public de.fraunhofer.isst.health.transit.utils.gpas.domain.DomainInUseExceptionType getFaultInfo() {
        return this.faultInfo;
    }
}
