
package de.fraunhofer.isst.health.transit.utils.gpas.domain;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-17T10:42:08.600Z
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidGeneratorException", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/")
public class InvalidGeneratorException extends Exception {

    private InvalidGeneratorExceptionType faultInfo;

    public InvalidGeneratorException() {
        super();
    }

    public InvalidGeneratorException(String message) {
        super(message);
    }

    public InvalidGeneratorException(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidGeneratorException(String message,
                                     InvalidGeneratorExceptionType invalidGeneratorException) {
        super(message);
        this.faultInfo = invalidGeneratorException;
    }

    public InvalidGeneratorException(String message,
                                     InvalidGeneratorExceptionType invalidGeneratorException,
                                     Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidGeneratorException;
    }

    public InvalidGeneratorExceptionType getFaultInfo() {
        return this.faultInfo;
    }
}
