
package de.fraunhofer.isst.health.transit.utils.gpas.domain;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-17T10:42:08.726Z
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidParentDomainException", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/")
public class InvalidParentDomainExceptionException extends Exception {

    private InvalidParentDomainException faultInfo;

    public InvalidParentDomainExceptionException() {
        super();
    }

    public InvalidParentDomainExceptionException(String message) {
        super(message);
    }

    public InvalidParentDomainExceptionException(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidParentDomainExceptionException(String message,
                                                 InvalidParentDomainException invalidParentDomainException) {
        super(message);
        this.faultInfo = invalidParentDomainException;
    }

    public InvalidParentDomainExceptionException(String message,
                                                 InvalidParentDomainException invalidParentDomainException,
                                                 Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidParentDomainException;
    }

    public InvalidParentDomainException getFaultInfo() {
        return this.faultInfo;
    }
}
