
package de.fraunhofer.isst.health.transit.utils.gpas.domain;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-17T10:42:08.577Z
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidCheckDigitClassException", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/")
public class InvalidCheckDigitClassException extends Exception {

    private de.fraunhofer.isst.health.transit.utils.gpas.domain.InvalidCheckDigitClassExceptionType faultInfo;

    public InvalidCheckDigitClassException() {
        super();
    }

    public InvalidCheckDigitClassException(String message) {
        super(message);
    }

    public InvalidCheckDigitClassException(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidCheckDigitClassException(String message,
                                           InvalidCheckDigitClassExceptionType invalidCheckDigitClassException) {
        super(message);
        this.faultInfo = invalidCheckDigitClassException;
    }

    public InvalidCheckDigitClassException(String message,
                                           InvalidCheckDigitClassExceptionType invalidCheckDigitClassException,
                                           Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidCheckDigitClassException;
    }

    public de.fraunhofer.isst.health.transit.utils.gpas.domain.InvalidCheckDigitClassExceptionType getFaultInfo() {
        return this.faultInfo;
    }
}
