
package de.fraunhofer.isst.health.transit.utils.gpas.domain;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-17T10:42:08.671Z
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidAlphabetException", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/")
public class InvalidAlphabetException extends Exception {

    private de.fraunhofer.isst.health.transit.utils.gpas.domain.InvalidAlphabetExceptionType faultInfo;

    public InvalidAlphabetException() {
        super();
    }

    public InvalidAlphabetException(String message) {
        super(message);
    }

    public InvalidAlphabetException(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidAlphabetException(String message,
                                    InvalidAlphabetExceptionType invalidAlphabetException) {
        super(message);
        this.faultInfo = invalidAlphabetException;
    }

    public InvalidAlphabetException(String message,
                                    InvalidAlphabetExceptionType invalidAlphabetException,
                                    Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidAlphabetException;
    }

    public de.fraunhofer.isst.health.transit.utils.gpas.domain.InvalidAlphabetExceptionType getFaultInfo() {
        return this.faultInfo;
    }
}
