
package de.fraunhofer.isst.health.transit.utils.gpas.domain;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-17T10:42:08.740Z
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidUpdateInUseOperationException", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/")
public class InvalidUpdateInUseOperationExceptionException extends Exception {

    private InvalidUpdateInUseOperationException faultInfo;

    public InvalidUpdateInUseOperationExceptionException() {
        super();
    }

    public InvalidUpdateInUseOperationExceptionException(String message) {
        super(message);
    }

    public InvalidUpdateInUseOperationExceptionException(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidUpdateInUseOperationExceptionException(String message,
                                                         InvalidUpdateInUseOperationException exception) {
        super(message);
        this.faultInfo = exception;
    }

    public InvalidUpdateInUseOperationExceptionException(String message,
                                                         InvalidUpdateInUseOperationException exception,
                                                         Throwable cause) {
        super(message, cause);
        this.faultInfo = exception;
    }

    public InvalidUpdateInUseOperationException getFaultInfo() {
        return this.faultInfo;
    }
}
