
package de.fraunhofer.isst.health.transit.utils.gpas.domain;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-17T10:42:08.468Z
 * Generated source version: 4.1.1
 */

@WebFault(name = "UnknownDomainException", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/")
public class UnknownDomainException extends Exception {

    private de.fraunhofer.isst.health.transit.utils.gpas.domain.UnknownDomainExceptionType faultInfo;

    public UnknownDomainException() {
        super();
    }

    public UnknownDomainException(String message) {
        super(message);
    }

    public UnknownDomainException(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownDomainException(String message,
                                  UnknownDomainExceptionType unknownDomainException) {
        super(message);
        this.faultInfo = unknownDomainException;
    }

    public UnknownDomainException(String message,
                                  UnknownDomainExceptionType unknownDomainException,
                                  Throwable cause) {
        super(message, cause);
        this.faultInfo = unknownDomainException;
    }

    public de.fraunhofer.isst.health.transit.utils.gpas.domain.UnknownDomainExceptionType getFaultInfo() {
        return this.faultInfo;
    }
}
