
package de.fraunhofer.isst.health.transit.utils.epix.services;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.2.3
 * 2026-10-07T14:46:59.290+02:00
 * Generated source version: 4.2.3
 */

@WebFault(name = "DuplicateEntryException", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/")
public class DuplicateEntryException_Exception extends Exception {

    private DuplicateEntryException faultInfo;

    public DuplicateEntryException_Exception() {
        super();
    }

    public DuplicateEntryException_Exception(String message) {
        super(message);
    }

    public DuplicateEntryException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public DuplicateEntryException_Exception(String message, DuplicateEntryException duplicateEntryException) {
        super(message);
        this.faultInfo = duplicateEntryException;
    }

    public DuplicateEntryException_Exception(String message, DuplicateEntryException duplicateEntryException, Throwable cause) {
        super(message, cause);
        this.faultInfo = duplicateEntryException;
    }

    public DuplicateEntryException getFaultInfo() {
        return this.faultInfo;
    }
}
