package de.fraunhofer.isst.health.transit.utils.epix.services;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;

import javax.xml.namespace.QName;
import java.net.URL;

/**
 * This class was generated by Apache CXF 4.2.3
 * 2026-10-07T14:46:58.650+02:00
 * Generated source version: 4.2.3
 *
 */
@WebServiceClient(name = "EPIXManagementServiceImplService",
                  wsdlLocation = "classpath:epixManagementService.wsdl",
                  targetNamespace = "http://service.epix.ttp.icmvc.emau.org/")
public class EPIXManagementServiceImplService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://service.epix.ttp.icmvc.emau.org/", "EPIXManagementServiceImplService");
    public static final QName EpixManagementServicePort = new QName("http://service.epix.ttp.icmvc.emau.org/", "epixManagementServicePort");
    static {
        URL url = EPIXManagementServiceImplService.class.getClassLoader().getResource("epixManagementService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(EPIXManagementServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:epixManagementService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EPIXManagementServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EPIXManagementServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EPIXManagementServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EPIXManagementServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EPIXManagementServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EPIXManagementServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EPIXManagementService
     */
    @WebEndpoint(name = "epixManagementServicePort")
    public EPIXManagementService getEpixManagementServicePort() {
        return super.getPort(EpixManagementServicePort, EPIXManagementService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EPIXManagementService
     */
    @WebEndpoint(name = "epixManagementServicePort")
    public EPIXManagementService getEpixManagementServicePort(WebServiceFeature... features) {
        return super.getPort(EpixManagementServicePort, EPIXManagementService.class, features);
    }

}
