package de.fraunhofer.isst.health.transit.utils.epix.services;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.2.3
 * 2026-10-07T14:46:58.601+02:00
 * Generated source version: 4.2.3
 *
 */
@WebService(targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", name = "EPIXManagementService")
@XmlSeeAlso({ObjectFactory.class})
public interface EPIXManagementService {

    @WebMethod
    @RequestWrapper(localName = "getIdentityHistoriesForDomainFiltered", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetIdentityHistoriesForDomainFiltered")
    @ResponseWrapper(localName = "getIdentityHistoriesForDomainFilteredResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetIdentityHistoriesForDomainFilteredResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<IdentityHistoryDTO> getIdentityHistoriesForDomainFiltered(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "filter", targetNamespace = "")
        GetIdentityHistoriesForDomainFiltered.Filter filter,
        @WebParam(name = "filterIsCaseSensitive", targetNamespace = "")
        boolean filterIsCaseSensitive
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getDeacticatedIdentitiesForDomain", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetDeacticatedIdentitiesForDomain")
    @ResponseWrapper(localName = "getDeacticatedIdentitiesForDomainResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetDeacticatedIdentitiesForDomainResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<IdentityOutDTO> getDeacticatedIdentitiesForDomain(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getIdentityHistoriesForDomain", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetIdentityHistoriesForDomain")
    @ResponseWrapper(localName = "getIdentityHistoriesForDomainResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetIdentityHistoriesForDomainResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<IdentityHistoryDTO> getIdentityHistoriesForDomain(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getDomains", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetDomains")
    @ResponseWrapper(localName = "getDomainsResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetDomainsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<DomainDTO> getDomains()
;

    @WebMethod
    @RequestWrapper(localName = "getIdentifierDomains", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetIdentifierDomains")
    @ResponseWrapper(localName = "getIdentifierDomainsResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetIdentifierDomainsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<IdentifierDomainDTO> getIdentifierDomains()
;

    @WebMethod
    @RequestWrapper(localName = "addDomain", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.AddDomain")
    @ResponseWrapper(localName = "addDomainResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.AddDomainResponse")
    @WebResult(name = "return", targetNamespace = "")
    public DomainDTO addDomain(

        @WebParam(name = "domain", targetNamespace = "")
        DomainDTO domain
    ) throws DuplicateEntryException_Exception, UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPossibleMatchHistoryForUpdatedIdentity", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPossibleMatchHistoryForUpdatedIdentity")
    @ResponseWrapper(localName = "getPossibleMatchHistoryForUpdatedIdentityResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPossibleMatchHistoryForUpdatedIdentityResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<PossibleMatchHistoryDTO> getPossibleMatchHistoryForUpdatedIdentity(

        @WebParam(name = "updatedIdentityId", targetNamespace = "")
        long updatedIdentityId
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getIdentityHistoryByPersonId", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetIdentityHistoryByPersonId")
    @ResponseWrapper(localName = "getIdentityHistoryByPersonIdResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetIdentityHistoryByPersonIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<IdentityHistoryDTO> getIdentityHistoryByPersonId(

        @WebParam(name = "personId", targetNamespace = "")
        long personId
    ) throws UnknownObjectException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getDomain", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetDomain")
    @ResponseWrapper(localName = "getDomainResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetDomainResponse")
    @WebResult(name = "return", targetNamespace = "")
    public DomainDTO getDomain(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getSource", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetSource")
    @ResponseWrapper(localName = "getSourceResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetSourceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public SourceDTO getSource(

        @WebParam(name = "sourceName", targetNamespace = "")
        String sourceName
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "updateSource", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.UpdateSource")
    @ResponseWrapper(localName = "updateSourceResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.UpdateSourceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public SourceDTO updateSource(

        @WebParam(name = "source", targetNamespace = "")
        SourceDTO source
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "encodeMatchingConfiguration", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.EncodeMatchingConfiguration")
    @ResponseWrapper(localName = "encodeMatchingConfigurationResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.EncodeMatchingConfigurationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String encodeMatchingConfiguration(

        @WebParam(name = "config", targetNamespace = "")
        ConfigurationContainer config
    ) throws MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "updateDomainInUse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.UpdateDomainInUse")
    @ResponseWrapper(localName = "updateDomainInUseResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.UpdateDomainInUseResponse")
    @WebResult(name = "return", targetNamespace = "")
    public DomainDTO updateDomainInUse(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "label", targetNamespace = "")
        String label,
        @WebParam(name = "description", targetNamespace = "")
        String description
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "parseMatchingConfiguration", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.ParseMatchingConfiguration")
    @ResponseWrapper(localName = "parseMatchingConfigurationResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.ParseMatchingConfigurationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ConfigurationContainer parseMatchingConfiguration(

        @WebParam(name = "xml", targetNamespace = "")
        String xml
    ) throws MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getDefinedDeduplicationReasons", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetDefinedDeduplicationReasons")
    @ResponseWrapper(localName = "getDefinedDeduplicationReasonsResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetDefinedDeduplicationReasonsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ReasonDTO> getDefinedDeduplicationReasons(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPossibleMatchHistoryForPerson", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPossibleMatchHistoryForPerson")
    @ResponseWrapper(localName = "getPossibleMatchHistoryForPersonResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPossibleMatchHistoryForPersonResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<PossibleMatchHistoryDTO> getPossibleMatchHistoryForPerson(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "mpiId", targetNamespace = "")
        String mpiId
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "updateDomain", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.UpdateDomain")
    @ResponseWrapper(localName = "updateDomainResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.UpdateDomainResponse")
    @WebResult(name = "return", targetNamespace = "")
    public DomainDTO updateDomain(

        @WebParam(name = "domain", targetNamespace = "")
        DomainDTO domain
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception, ObjectInUseException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getHistoryForIdentity", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetHistoryForIdentity")
    @ResponseWrapper(localName = "getHistoryForIdentityResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetHistoryForIdentityResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<IdentityHistoryDTO> getHistoryForIdentity(

        @WebParam(name = "identityId", targetNamespace = "")
        long identityId
    ) throws UnknownObjectException_Exception;

    @WebMethod
    @RequestWrapper(localName = "deleteIdentifierDomain", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.DeleteIdentifierDomain")
    @ResponseWrapper(localName = "deleteIdentifierDomainResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.DeleteIdentifierDomainResponse")
    public void deleteIdentifierDomain(

        @WebParam(name = "identifierDomainName", targetNamespace = "")
        String identifierDomainName
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception, ObjectInUseException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getIdentityHistoriesForDomainPaginated", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetIdentityHistoriesForDomainPaginated")
    @ResponseWrapper(localName = "getIdentityHistoriesForDomainPaginatedResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetIdentityHistoriesForDomainPaginatedResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<IdentityHistoryDTO> getIdentityHistoriesForDomainPaginated(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "paginationConfig", targetNamespace = "")
        PaginationConfig paginationConfig
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "countPossibleMatchHistoriesForDomain", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.CountPossibleMatchHistoriesForDomain")
    @ResponseWrapper(localName = "countPossibleMatchHistoriesForDomainResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.CountPossibleMatchHistoriesForDomainResponse")
    @WebResult(name = "return", targetNamespace = "")
    public long countPossibleMatchHistoriesForDomain(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "paginationConfig", targetNamespace = "")
        PaginationConfig paginationConfig
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getHistoryForContact", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetHistoryForContact")
    @ResponseWrapper(localName = "getHistoryForContactResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetHistoryForContactResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ContactHistoryDTO> getHistoryForContact(

        @WebParam(name = "contactId", targetNamespace = "")
        long contactId
    ) throws UnknownObjectException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getIdentifierDomain", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetIdentifierDomain")
    @ResponseWrapper(localName = "getIdentifierDomainResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetIdentifierDomainResponse")
    @WebResult(name = "return", targetNamespace = "")
    public IdentifierDomainDTO getIdentifierDomain(

        @WebParam(name = "identifierDomainName", targetNamespace = "")
        String identifierDomainName
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getDeactivatedPersonsForDomain", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetDeactivatedPersonsForDomain")
    @ResponseWrapper(localName = "getDeactivatedPersonsForDomainResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetDeactivatedPersonsForDomainResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<PersonDTO> getDeactivatedPersonsForDomain(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getConfigurationForDomain", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetConfigurationForDomain")
    @ResponseWrapper(localName = "getConfigurationForDomainResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetConfigurationForDomainResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ConfigurationContainer getConfigurationForDomain(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "deleteSource", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.DeleteSource")
    @ResponseWrapper(localName = "deleteSourceResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.DeleteSourceResponse")
    public void deleteSource(

        @WebParam(name = "sourceName", targetNamespace = "")
        String sourceName
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception, ObjectInUseException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getSources", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetSources")
    @ResponseWrapper(localName = "getSourcesResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetSourcesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<SourceDTO> getSources()
;

    @WebMethod
    @RequestWrapper(localName = "countIdentityHistoriesForDomain", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.CountIdentityHistoriesForDomain")
    @ResponseWrapper(localName = "countIdentityHistoriesForDomainResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.CountIdentityHistoriesForDomainResponse")
    @WebResult(name = "return", targetNamespace = "")
    public long countIdentityHistoriesForDomain(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "paginationConfig", targetNamespace = "")
        PaginationConfig paginationConfig
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPossibleMatchHistoryByIdentity", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPossibleMatchHistoryByIdentity")
    @ResponseWrapper(localName = "getPossibleMatchHistoryByIdentityResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPossibleMatchHistoryByIdentityResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<PossibleMatchHistoryDTO> getPossibleMatchHistoryByIdentity(

        @WebParam(name = "identityId", targetNamespace = "")
        long identityId
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPersonById", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPersonById")
    @ResponseWrapper(localName = "getPersonByIdResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPersonByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public PersonDTO getPersonById(

        @WebParam(name = "id", targetNamespace = "")
        long id
    ) throws UnknownObjectException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getHistoryForPerson", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetHistoryForPerson")
    @ResponseWrapper(localName = "getHistoryForPersonResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetHistoryForPersonResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<PersonHistoryDTO> getHistoryForPerson(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "mpiId", targetNamespace = "")
        String mpiId
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getHistoryForIdentifier", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetHistoryForIdentifier")
    @ResponseWrapper(localName = "getHistoryForIdentifierResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetHistoryForIdentifierResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<IdentifierHistoryDTO> getHistoryForIdentifier(

        @WebParam(name = "identifierDomainName", targetNamespace = "")
        String identifierDomainName,
        @WebParam(name = "identifierValue", targetNamespace = "")
        String identifierValue
    ) throws UnknownObjectException_Exception;

    @WebMethod
    @RequestWrapper(localName = "updateIdentifierDomain", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.UpdateIdentifierDomain")
    @ResponseWrapper(localName = "updateIdentifierDomainResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.UpdateIdentifierDomainResponse")
    @WebResult(name = "return", targetNamespace = "")
    public IdentifierDomainDTO updateIdentifierDomain(

        @WebParam(name = "identifierDomain", targetNamespace = "")
        IdentifierDomainDTO identifierDomain
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "addSource", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.AddSource")
    @ResponseWrapper(localName = "addSourceResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.AddSourceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public SourceDTO addSource(

        @WebParam(name = "source", targetNamespace = "")
        SourceDTO source
    ) throws DuplicateEntryException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "addIdentifierDomain", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.AddIdentifierDomain")
    @ResponseWrapper(localName = "addIdentifierDomainResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.AddIdentifierDomainResponse")
    @WebResult(name = "return", targetNamespace = "")
    public IdentifierDomainDTO addIdentifierDomain(

        @WebParam(name = "identifierDomain", targetNamespace = "")
        IdentifierDomainDTO identifierDomain
    ) throws DuplicateEntryException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "deleteDomain", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.DeleteDomain")
    @ResponseWrapper(localName = "deleteDomainResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.DeleteDomainResponse")
    public void deleteDomain(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "force", targetNamespace = "")
        boolean force
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception, ObjectInUseException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getIdentityById", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetIdentityById")
    @ResponseWrapper(localName = "getIdentityByIdResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetIdentityByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public IdentityOutDTO getIdentityById(

        @WebParam(name = "id", targetNamespace = "")
        long id
    ) throws UnknownObjectException_Exception;
}
