package de.fraunhofer.isst.health.transit.utils.epix.services;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;

import javax.xml.namespace.QName;
import java.net.URL;

/**
 * This class was generated by Apache CXF 4.2.3
 * 2026-10-07T14:46:59.328+02:00
 * Generated source version: 4.2.3
 *
 */
@WebServiceClient(name = "EPIXServiceImplService",
                  wsdlLocation = "classpath:epixService.wsdl",
                  targetNamespace = "http://service.epix.ttp.icmvc.emau.org/")
public class EPIXServiceImplService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://service.epix.ttp.icmvc.emau.org/", "EPIXServiceImplService");
    public static final QName EpixServicePort = new QName("http://service.epix.ttp.icmvc.emau.org/", "epixServicePort");
    static {
        URL url = EPIXServiceImplService.class.getClassLoader().getResource("epixService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(EPIXServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:epixService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EPIXServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EPIXServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EPIXServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EPIXServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EPIXServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EPIXServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EPIXService
     */
    @WebEndpoint(name = "epixServicePort")
    public EPIXService getEpixServicePort() {
        return super.getPort(EpixServicePort, EPIXService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EPIXService
     */
    @WebEndpoint(name = "epixServicePort")
    public EPIXService getEpixServicePort(WebServiceFeature... features) {
        return super.getPort(EpixServicePort, EPIXService.class, features);
    }

}
