package de.fraunhofer.isst.health.transit.utils.epix.services;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.2.3
 * 2026-10-07T14:46:59.296+02:00
 * Generated source version: 4.2.3
 *
 */
@WebService(targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", name = "EPIXService")
@XmlSeeAlso({ObjectFactory.class})
public interface EPIXService {

    @WebMethod
    @RequestWrapper(localName = "deactivateIdentity", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.DeactivateIdentity")
    @ResponseWrapper(localName = "deactivateIdentityResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.DeactivateIdentityResponse")
    public void deactivateIdentity(

        @WebParam(name = "identityId", targetNamespace = "")
        long identityId
    ) throws UnknownObjectException_Exception, MPIException_Exception;

    @WebMethod
    @RequestWrapper(localName = "requestMPI", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.RequestMPI")
    @ResponseWrapper(localName = "requestMPIResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.RequestMPIResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ResponseEntryDTO requestMPI(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "identity", targetNamespace = "")
        IdentityInDTO identity,
        @WebParam(name = "sourceName", targetNamespace = "")
        String sourceName,
        @WebParam(name = "comment", targetNamespace = "")
        String comment
    ) throws ValidatorException_Exception, UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.DeletePersonResponse")
    public void deletePerson(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "mpiId", targetNamespace = "")
        String mpiId
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception, IllegalOperationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPersonByLocalIdentifier", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPersonByLocalIdentifier")
    @ResponseWrapper(localName = "getPersonByLocalIdentifierResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPersonByLocalIdentifierResponse")
    @WebResult(name = "return", targetNamespace = "")
    public PersonDTO getPersonByLocalIdentifier(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "identifier", targetNamespace = "")
        IdentifierDTO identifier
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPersonByMultipleLocalIdentifier", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPersonByMultipleLocalIdentifier")
    @ResponseWrapper(localName = "getPersonByMultipleLocalIdentifierResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPersonByMultipleLocalIdentifierResponse")
    @WebResult(name = "return", targetNamespace = "")
    public PersonDTO getPersonByMultipleLocalIdentifier(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "identifier", targetNamespace = "")
        java.util.List<IdentifierDTO> identifier,
        @WebParam(name = "allIdentifierRequired", targetNamespace = "")
        boolean allIdentifierRequired
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "setReferenceIdentity", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.SetReferenceIdentity")
    @ResponseWrapper(localName = "setReferenceIdentityResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.SetReferenceIdentityResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ResponseEntryDTO setReferenceIdentity(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "mpiId", targetNamespace = "")
        String mpiId,
        @WebParam(name = "identityId", targetNamespace = "")
        long identityId,
        @WebParam(name = "comment", targetNamespace = "")
        String comment
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "removePossibleMatches", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.RemovePossibleMatches")
    @ResponseWrapper(localName = "removePossibleMatchesResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.RemovePossibleMatchesResponse")
    public void removePossibleMatches(

        @WebParam(name = "possibleMatchIds", targetNamespace = "")
        java.util.List<Long> possibleMatchIds,
        @WebParam(name = "comment", targetNamespace = "")
        String comment
    ) throws MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPersonByMPI", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPersonByMPI")
    @ResponseWrapper(localName = "getPersonByMPIResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPersonByMPIResponse")
    @WebResult(name = "return", targetNamespace = "")
    public PersonDTO getPersonByMPI(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "mpiId", targetNamespace = "")
        String mpiId
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getAllIdentifierForAcivePersonWithMPI", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetAllIdentifierForAcivePersonWithMPI")
    @ResponseWrapper(localName = "getAllIdentifierForAcivePersonWithMPIResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetAllIdentifierForAcivePersonWithMPIResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<IdentifierDTO> getAllIdentifierForAcivePersonWithMPI(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "mpiId", targetNamespace = "")
        String mpiId
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "countPossibleMatchesForDomain", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.CountPossibleMatchesForDomain")
    @ResponseWrapper(localName = "countPossibleMatchesForDomainResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.CountPossibleMatchesForDomainResponse")
    @WebResult(name = "return", targetNamespace = "")
    public long countPossibleMatchesForDomain(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "removePossibleMatch", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.RemovePossibleMatch")
    @ResponseWrapper(localName = "removePossibleMatchResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.RemovePossibleMatchResponse")
    public void removePossibleMatch(

        @WebParam(name = "possibleMatchId", targetNamespace = "")
        long possibleMatchId,
        @WebParam(name = "comment", targetNamespace = "")
        String comment
    ) throws MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getAllMPIFromPersonByMPI", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetAllMPIFromPersonByMPI")
    @ResponseWrapper(localName = "getAllMPIFromPersonByMPIResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetAllMPIFromPersonByMPIResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<String> getAllMPIFromPersonByMPI(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "mpiId", targetNamespace = "")
        String mpiId
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPersonsForDomainFiltered", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPersonsForDomainFiltered")
    @ResponseWrapper(localName = "getPersonsForDomainFilteredResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPersonsForDomainFilteredResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<PersonDTO> getPersonsForDomainFiltered(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "filter", targetNamespace = "")
        GetPersonsForDomainFiltered.Filter filter,
        @WebParam(name = "filterIsCaseSensitive", targetNamespace = "")
        boolean filterIsCaseSensitive
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getAllMPIFromActivePersonByMPI", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetAllMPIFromActivePersonByMPI")
    @ResponseWrapper(localName = "getAllMPIFromActivePersonByMPIResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetAllMPIFromActivePersonByMPIResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<String> getAllMPIFromActivePersonByMPI(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "mpiId", targetNamespace = "")
        String mpiId
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getActivePersonsForDomainPaginated", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetActivePersonsForDomainPaginated")
    @ResponseWrapper(localName = "getActivePersonsForDomainPaginatedResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetActivePersonsForDomainPaginatedResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<PersonDTO> getActivePersonsForDomainPaginated(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "firstEntry", targetNamespace = "")
        int firstEntry,
        @WebParam(name = "pageSize", targetNamespace = "")
        int pageSize,
        @WebParam(name = "sortField", targetNamespace = "")
        String sortField,
        @WebParam(name = "sortIsAscending", targetNamespace = "")
        boolean sortIsAscending,
        @WebParam(name = "filter", targetNamespace = "")
        GetActivePersonsForDomainPaginated.Filter filter,
        @WebParam(name = "filterIsCaseSensitive", targetNamespace = "")
        boolean filterIsCaseSensitive
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "moveIdentitiesForIdentifierToPerson", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.MoveIdentitiesForIdentifierToPerson")
    @ResponseWrapper(localName = "moveIdentitiesForIdentifierToPersonResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.MoveIdentitiesForIdentifierToPersonResponse")
    public void moveIdentitiesForIdentifierToPerson(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "identifier", targetNamespace = "")
        IdentifierDTO identifier,
        @WebParam(name = "mpiId", targetNamespace = "")
        String mpiId,
        @WebParam(name = "comment", targetNamespace = "")
        String comment
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "deleteIdentity", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.DeleteIdentity")
    @ResponseWrapper(localName = "deleteIdentityResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.DeleteIdentityResponse")
    public void deleteIdentity(

        @WebParam(name = "identityId", targetNamespace = "")
        long identityId
    ) throws UnknownObjectException_Exception, MPIException_Exception, IllegalOperationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "addLocalIdentifierToMPI", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.AddLocalIdentifierToMPI")
    @ResponseWrapper(localName = "addLocalIdentifierToMPIResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.AddLocalIdentifierToMPIResponse")
    public void addLocalIdentifierToMPI(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "mpiId", targetNamespace = "")
        String mpiId,
        @WebParam(name = "localIds", targetNamespace = "")
        java.util.List<IdentifierDTO> localIds
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getActivePersonsForDomain", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetActivePersonsForDomain")
    @ResponseWrapper(localName = "getActivePersonsForDomainResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetActivePersonsForDomainResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<PersonDTO> getActivePersonsForDomain(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "searchPersonsByPDQ", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.SearchPersonsByPDQ")
    @ResponseWrapper(localName = "searchPersonsByPDQResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.SearchPersonsByPDQResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<PersonDTO> searchPersonsByPDQ(

        @WebParam(name = "searchMask", targetNamespace = "")
        SearchMask searchMask
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "deactivatePerson", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.DeactivatePerson")
    @ResponseWrapper(localName = "deactivatePersonResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.DeactivatePersonResponse")
    public void deactivatePerson(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "mpiId", targetNamespace = "")
        String mpiId
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getMPIForIdentifier", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetMPIForIdentifier")
    @ResponseWrapper(localName = "getMPIForIdentifierResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetMPIForIdentifierResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getMPIForIdentifier(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "identifier", targetNamespace = "")
        IdentifierDTO identifier
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getActivePersonByMPI", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetActivePersonByMPI")
    @ResponseWrapper(localName = "getActivePersonByMPIResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetActivePersonByMPIResponse")
    @WebResult(name = "return", targetNamespace = "")
    public PersonDTO getActivePersonByMPI(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "mpiId", targetNamespace = "")
        String mpiId
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "addLocalIdentifierToActivePersonWithMPI", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.AddLocalIdentifierToActivePersonWithMPI")
    @ResponseWrapper(localName = "addLocalIdentifierToActivePersonWithMPIResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.AddLocalIdentifierToActivePersonWithMPIResponse")
    public void addLocalIdentifierToActivePersonWithMPI(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "mpiId", targetNamespace = "")
        String mpiId,
        @WebParam(name = "localIds", targetNamespace = "")
        java.util.List<IdentifierDTO> localIds
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getActivePersonsByMPIBatch", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetActivePersonsByMPIBatch")
    @ResponseWrapper(localName = "getActivePersonsByMPIBatchResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetActivePersonsByMPIBatchResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<PersonDTO> getActivePersonsByMPIBatch(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "mpiIds", targetNamespace = "")
        java.util.List<String> mpiIds
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "deactivateContact", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.DeactivateContact")
    @ResponseWrapper(localName = "deactivateContactResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.DeactivateContactResponse")
    public void deactivateContact(

        @WebParam(name = "contactId", targetNamespace = "")
        long contactId
    ) throws UnknownObjectException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPersonsForDomain", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPersonsForDomain")
    @ResponseWrapper(localName = "getPersonsForDomainResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPersonsForDomainResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<PersonDTO> getPersonsForDomain(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getAllIdentifierForMPI", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetAllIdentifierForMPI")
    @ResponseWrapper(localName = "getAllIdentifierForMPIResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetAllIdentifierForMPIResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<IdentifierDTO> getAllIdentifierForMPI(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "mpiId", targetNamespace = "")
        String mpiId
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "requestMPIBatch", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.RequestMPIBatch")
    @ResponseWrapper(localName = "requestMPIBatchResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.RequestMPIBatchResponse")
    @WebResult(name = "return", targetNamespace = "")
    public MpiResponseDTO requestMPIBatch(

        @WebParam(name = "mpiRequest", targetNamespace = "")
        MpiRequestDTO mpiRequest
    ) throws ValidatorException_Exception, UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "countPossibleMatchesForDomainFiltered", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.CountPossibleMatchesForDomainFiltered")
    @ResponseWrapper(localName = "countPossibleMatchesForDomainFilteredResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.CountPossibleMatchesForDomainFilteredResponse")
    @WebResult(name = "return", targetNamespace = "")
    public long countPossibleMatchesForDomainFiltered(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "paginationConfig", targetNamespace = "")
        PaginationConfig paginationConfig
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "externalPossibleMatchForIdentity", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.ExternalPossibleMatchForIdentity")
    @ResponseWrapper(localName = "externalPossibleMatchForIdentityResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.ExternalPossibleMatchForIdentityResponse")
    @WebResult(name = "return", targetNamespace = "")
    public PossibleMatchDTO externalPossibleMatchForIdentity(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "identityId", targetNamespace = "")
        long identityId,
        @WebParam(name = "aliasIdentityId", targetNamespace = "")
        long aliasIdentityId
    ) throws DuplicateEntryException_Exception, UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getIdentitiesForDomain", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetIdentitiesForDomain")
    @ResponseWrapper(localName = "getIdentitiesForDomainResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetIdentitiesForDomainResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<IdentityOutDTO> getIdentitiesForDomain(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "removeLocalIdentifier", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.RemoveLocalIdentifier")
    @ResponseWrapper(localName = "removeLocalIdentifierResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.RemoveLocalIdentifierResponse")
    @WebResult(name = "_return", targetNamespace = "")
    public RemoveLocalIdentifierResponse.Return removeLocalIdentifier(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "localIds", targetNamespace = "")
        java.util.List<IdentifierDTO> localIds
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "updatePrivacy", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.UpdatePrivacy")
    @ResponseWrapper(localName = "updatePrivacyResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.UpdatePrivacyResponse")
    public void updatePrivacy(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "mpiIds", targetNamespace = "")
        java.util.List<String> mpiIds,
        @WebParam(name = "onlyReferenceIdentity", targetNamespace = "")
        boolean onlyReferenceIdentity
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getActivePersonsForDomainFiltered", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetActivePersonsForDomainFiltered")
    @ResponseWrapper(localName = "getActivePersonsForDomainFilteredResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetActivePersonsForDomainFilteredResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<PersonDTO> getActivePersonsForDomainFiltered(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "filter", targetNamespace = "")
        GetActivePersonsForDomainFiltered.Filter filter,
        @WebParam(name = "filterIsCaseSensitive", targetNamespace = "")
        boolean filterIsCaseSensitive
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPersonsByMPIBatch", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPersonsByMPIBatch")
    @ResponseWrapper(localName = "getPersonsByMPIBatchResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPersonsByMPIBatchResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<PersonDTO> getPersonsByMPIBatch(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "mpiIds", targetNamespace = "")
        java.util.List<String> mpiIds
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPersonsForDomainPaginated", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPersonsForDomainPaginated")
    @ResponseWrapper(localName = "getPersonsForDomainPaginatedResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPersonsForDomainPaginatedResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<PersonDTO> getPersonsForDomainPaginated(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "firstEntry", targetNamespace = "")
        int firstEntry,
        @WebParam(name = "pageSize", targetNamespace = "")
        int pageSize,
        @WebParam(name = "sortField", targetNamespace = "")
        String sortField,
        @WebParam(name = "sortIsAscending", targetNamespace = "")
        boolean sortIsAscending,
        @WebParam(name = "filter", targetNamespace = "")
        GetPersonsForDomainPaginated.Filter filter,
        @WebParam(name = "filterIsCaseSensitive", targetNamespace = "")
        boolean filterIsCaseSensitive
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPossibleMatchesForDomainFiltered", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPossibleMatchesForDomainFiltered")
    @ResponseWrapper(localName = "getPossibleMatchesForDomainFilteredResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPossibleMatchesForDomainFilteredResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<PossibleMatchDTO> getPossibleMatchesForDomainFiltered(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "paginationConfig", targetNamespace = "")
        PaginationConfig paginationConfig
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "updateActivePersonWithConfig", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.UpdateActivePersonWithConfig")
    @ResponseWrapper(localName = "updateActivePersonWithConfigResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.UpdateActivePersonWithConfigResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ResponseEntryDTO updateActivePersonWithConfig(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "mpiId", targetNamespace = "")
        String mpiId,
        @WebParam(name = "identity", targetNamespace = "")
        IdentityInDTO identity,
        @WebParam(name = "sourceName", targetNamespace = "")
        String sourceName,
        @WebParam(name = "force", targetNamespace = "")
        boolean force,
        @WebParam(name = "comment", targetNamespace = "")
        String comment,
        @WebParam(name = "requestConfig", targetNamespace = "")
        RequestConfig requestConfig,
        @WebParam(name = "updateBehaviour", targetNamespace = "")
        String updateBehaviour
    ) throws ValidatorException_Exception, UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "deleteContact", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.DeleteContact")
    @ResponseWrapper(localName = "deleteContactResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.DeleteContactResponse")
    public void deleteContact(

        @WebParam(name = "contactId", targetNamespace = "")
        long contactId
    ) throws UnknownObjectException_Exception, IllegalOperationException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getActivePersonByLocalIdentifier", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetActivePersonByLocalIdentifier")
    @ResponseWrapper(localName = "getActivePersonByLocalIdentifierResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetActivePersonByLocalIdentifierResponse")
    @WebResult(name = "return", targetNamespace = "")
    public PersonDTO getActivePersonByLocalIdentifier(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "identifier", targetNamespace = "")
        IdentifierDTO identifier
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "addLocalIdentifierToIdentifier", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.AddLocalIdentifierToIdentifier")
    @ResponseWrapper(localName = "addLocalIdentifierToIdentifierResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.AddLocalIdentifierToIdentifierResponse")
    public void addLocalIdentifierToIdentifier(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "identifier", targetNamespace = "")
        IdentifierDTO identifier,
        @WebParam(name = "localIds", targetNamespace = "")
        java.util.List<IdentifierDTO> localIds
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getIdentitiesForDomainFiltered", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetIdentitiesForDomainFiltered")
    @ResponseWrapper(localName = "getIdentitiesForDomainFilteredResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetIdentitiesForDomainFilteredResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<IdentityOutDTO> getIdentitiesForDomainFiltered(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "filter", targetNamespace = "")
        GetIdentitiesForDomainFiltered.Filter filter,
        @WebParam(name = "filterIsCaseSensitive", targetNamespace = "")
        boolean filterIsCaseSensitive
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "updatePersonWithConfig", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.UpdatePersonWithConfig")
    @ResponseWrapper(localName = "updatePersonWithConfigResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.UpdatePersonWithConfigResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ResponseEntryDTO updatePersonWithConfig(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "mpiId", targetNamespace = "")
        String mpiId,
        @WebParam(name = "identity", targetNamespace = "")
        IdentityInDTO identity,
        @WebParam(name = "sourceName", targetNamespace = "")
        String sourceName,
        @WebParam(name = "force", targetNamespace = "")
        boolean force,
        @WebParam(name = "comment", targetNamespace = "")
        String comment,
        @WebParam(name = "requestConfig", targetNamespace = "")
        RequestConfig requestConfig,
        @WebParam(name = "updateBehaviour", targetNamespace = "")
        String updateBehaviour
    ) throws ValidatorException_Exception, UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "assignIdentity", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.AssignIdentity")
    @ResponseWrapper(localName = "assignIdentityResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.AssignIdentityResponse")
    public void assignIdentity(

        @WebParam(name = "possibleMatchId", targetNamespace = "")
        long possibleMatchId,
        @WebParam(name = "winningIdentityId", targetNamespace = "")
        long winningIdentityId,
        @WebParam(name = "comment", targetNamespace = "")
        String comment
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPossibleMatchesForPerson", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPossibleMatchesForPerson")
    @ResponseWrapper(localName = "getPossibleMatchesForPersonResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPossibleMatchesForPersonResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<PossibleMatchForMPIDTO> getPossibleMatchesForPerson(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "mpiId", targetNamespace = "")
        String mpiId
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "countActivePersonsForDomainFiltered", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.CountActivePersonsForDomainFiltered")
    @ResponseWrapper(localName = "countActivePersonsForDomainFilteredResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.CountActivePersonsForDomainFilteredResponse")
    @WebResult(name = "return", targetNamespace = "")
    public long countActivePersonsForDomainFiltered(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "filter", targetNamespace = "")
        CountActivePersonsForDomainFiltered.Filter filter,
        @WebParam(name = "filterIsCaseSensitive", targetNamespace = "")
        boolean filterIsCaseSensitive
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPersonByFirstMPI", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPersonByFirstMPI")
    @ResponseWrapper(localName = "getPersonByFirstMPIResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPersonByFirstMPIResponse")
    @WebResult(name = "return", targetNamespace = "")
    public PersonDTO getPersonByFirstMPI(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "mpiId", targetNamespace = "")
        String mpiId
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPossibleMatchesForDomain", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPossibleMatchesForDomain")
    @ResponseWrapper(localName = "getPossibleMatchesForDomainResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPossibleMatchesForDomainResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<PossibleMatchDTO> getPossibleMatchesForDomain(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getIdentitiesForDomainPaginated", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetIdentitiesForDomainPaginated")
    @ResponseWrapper(localName = "getIdentitiesForDomainPaginatedResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetIdentitiesForDomainPaginatedResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<IdentityOutDTO> getIdentitiesForDomainPaginated(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "firstEntry", targetNamespace = "")
        int firstEntry,
        @WebParam(name = "pageSize", targetNamespace = "")
        int pageSize,
        @WebParam(name = "sortField", targetNamespace = "")
        String sortField,
        @WebParam(name = "sortIsAscending", targetNamespace = "")
        boolean sortIsAscending,
        @WebParam(name = "filter", targetNamespace = "")
        GetIdentitiesForDomainPaginated.Filter filter,
        @WebParam(name = "filterIsCaseSensitive", targetNamespace = "")
        boolean filterIsCaseSensitive
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getAllIdentifierForIdentifier", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetAllIdentifierForIdentifier")
    @ResponseWrapper(localName = "getAllIdentifierForIdentifierResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetAllIdentifierForIdentifierResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<IdentifierDTO> getAllIdentifierForIdentifier(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "identifier", targetNamespace = "")
        IdentifierDTO identifier
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "updateActivePerson", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.UpdateActivePerson")
    @ResponseWrapper(localName = "updateActivePersonResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.UpdateActivePersonResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ResponseEntryDTO updateActivePerson(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "mpiId", targetNamespace = "")
        String mpiId,
        @WebParam(name = "identity", targetNamespace = "")
        IdentityInDTO identity,
        @WebParam(name = "sourceName", targetNamespace = "")
        String sourceName,
        @WebParam(name = "force", targetNamespace = "")
        boolean force,
        @WebParam(name = "comment", targetNamespace = "")
        String comment,
        @WebParam(name = "updateBehaviour", targetNamespace = "")
        String updateBehaviour
    ) throws ValidatorException_Exception, UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.UpdatePersonResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ResponseEntryDTO updatePerson(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "mpiId", targetNamespace = "")
        String mpiId,
        @WebParam(name = "identity", targetNamespace = "")
        IdentityInDTO identity,
        @WebParam(name = "sourceName", targetNamespace = "")
        String sourceName,
        @WebParam(name = "force", targetNamespace = "")
        boolean force,
        @WebParam(name = "comment", targetNamespace = "")
        String comment,
        @WebParam(name = "updateBehaviour", targetNamespace = "")
        String updateBehaviour
    ) throws ValidatorException_Exception, UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPersonsByFirstMPIBatch", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPersonsByFirstMPIBatch")
    @ResponseWrapper(localName = "getPersonsByFirstMPIBatchResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetPersonsByFirstMPIBatchResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<PersonDTO> getPersonsByFirstMPIBatch(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "mpiIds", targetNamespace = "")
        java.util.List<String> mpiIds
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "countIdentitiesForDomainFiltered", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.CountIdentitiesForDomainFiltered")
    @ResponseWrapper(localName = "countIdentitiesForDomainFilteredResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.CountIdentitiesForDomainFilteredResponse")
    @WebResult(name = "return", targetNamespace = "")
    public long countIdentitiesForDomainFiltered(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "filter", targetNamespace = "")
        CountIdentitiesForDomainFiltered.Filter filter,
        @WebParam(name = "filterIsCaseSensitive", targetNamespace = "")
        boolean filterIsCaseSensitive
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "addContact", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.AddContact")
    @ResponseWrapper(localName = "addContactResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.AddContactResponse")
    @WebResult(name = "return", targetNamespace = "")
    public IdentityOutDTO addContact(

        @WebParam(name = "identityId", targetNamespace = "")
        long identityId,
        @WebParam(name = "contact", targetNamespace = "")
        ContactInDTO contact
    ) throws DuplicateEntryException_Exception, UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "addPerson", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.AddPerson")
    @ResponseWrapper(localName = "addPersonResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.AddPersonResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ResponseEntryDTO addPerson(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "identity", targetNamespace = "")
        IdentityInDTO identity,
        @WebParam(name = "sourceName", targetNamespace = "")
        String sourceName,
        @WebParam(name = "comment", targetNamespace = "")
        String comment
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "prioritizePossibleMatch", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.PrioritizePossibleMatch")
    @ResponseWrapper(localName = "prioritizePossibleMatchResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.PrioritizePossibleMatchResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean prioritizePossibleMatch(

        @WebParam(name = "linkId", targetNamespace = "")
        long linkId,
        @WebParam(name = "priority", targetNamespace = "")
        String priority
    ) throws MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "requestMPIWithConfig", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.RequestMPIWithConfig")
    @ResponseWrapper(localName = "requestMPIWithConfigResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.RequestMPIWithConfigResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ResponseEntryDTO requestMPIWithConfig(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "identity", targetNamespace = "")
        IdentityInDTO identity,
        @WebParam(name = "sourceName", targetNamespace = "")
        String sourceName,
        @WebParam(name = "comment", targetNamespace = "")
        String comment,
        @WebParam(name = "requestConfig", targetNamespace = "")
        RequestConfig requestConfig
    ) throws ValidatorException_Exception, UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "countPersonsForDomainFiltered", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.CountPersonsForDomainFiltered")
    @ResponseWrapper(localName = "countPersonsForDomainFilteredResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.CountPersonsForDomainFilteredResponse")
    @WebResult(name = "return", targetNamespace = "")
    public long countPersonsForDomainFiltered(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "filter", targetNamespace = "")
        CountPersonsForDomainFiltered.Filter filter,
        @WebParam(name = "filterIsCaseSensitive", targetNamespace = "")
        boolean filterIsCaseSensitive
    ) throws UnknownObjectException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getActivePersonByMultipleLocalIdentifier", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetActivePersonByMultipleLocalIdentifier")
    @ResponseWrapper(localName = "getActivePersonByMultipleLocalIdentifierResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.GetActivePersonByMultipleLocalIdentifierResponse")
    @WebResult(name = "return", targetNamespace = "")
    public PersonDTO getActivePersonByMultipleLocalIdentifier(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "identifier", targetNamespace = "")
        java.util.List<IdentifierDTO> identifier,
        @WebParam(name = "allIdentifierRequired", targetNamespace = "")
        boolean allIdentifierRequired
    ) throws UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;

    @WebMethod
    @RequestWrapper(localName = "externalPossibleMatchForPerson", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.ExternalPossibleMatchForPerson")
    @ResponseWrapper(localName = "externalPossibleMatchForPersonResponse", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/", className = "de.fraunhofer.isst.health.transit.utils.epix.services.ExternalPossibleMatchForPersonResponse")
    @WebResult(name = "return", targetNamespace = "")
    public PossibleMatchDTO externalPossibleMatchForPerson(

        @WebParam(name = "domainName", targetNamespace = "")
        String domainName,
        @WebParam(name = "mpiId", targetNamespace = "")
        String mpiId,
        @WebParam(name = "aliasMpiId", targetNamespace = "")
        String aliasMpiId
    ) throws DuplicateEntryException_Exception, UnknownObjectException_Exception, MPIException_Exception, InvalidParameterException_Exception;
}
