
package de.fraunhofer.isst.health.transit.utils.epix.services;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.2.3
 * 2026-10-07T14:46:59.283+02:00
 * Generated source version: 4.2.3
 */

@WebFault(name = "IllegalOperationException", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/")
public class IllegalOperationException_Exception extends Exception {

    private IllegalOperationException faultInfo;

    public IllegalOperationException_Exception() {
        super();
    }

    public IllegalOperationException_Exception(String message) {
        super(message);
    }

    public IllegalOperationException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public IllegalOperationException_Exception(String message, IllegalOperationException illegalOperationException) {
        super(message);
        this.faultInfo = illegalOperationException;
    }

    public IllegalOperationException_Exception(String message, IllegalOperationException illegalOperationException, Throwable cause) {
        super(message, cause);
        this.faultInfo = illegalOperationException;
    }

    public IllegalOperationException getFaultInfo() {
        return this.faultInfo;
    }
}
