
package de.fraunhofer.isst.health.transit.utils.epix.services;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.2.3
 * 2026-10-07T14:46:59.276+02:00
 * Generated source version: 4.2.3
 */

@WebFault(name = "InvalidParameterException", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/")
public class InvalidParameterException_Exception extends Exception {

    private InvalidParameterException faultInfo;

    public InvalidParameterException_Exception() {
        super();
    }

    public InvalidParameterException_Exception(String message) {
        super(message);
    }

    public InvalidParameterException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidParameterException_Exception(String message, InvalidParameterException invalidParameterException) {
        super(message);
        this.faultInfo = invalidParameterException;
    }

    public InvalidParameterException_Exception(String message, InvalidParameterException invalidParameterException, Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidParameterException;
    }

    public InvalidParameterException getFaultInfo() {
        return this.faultInfo;
    }
}
