
package de.fraunhofer.isst.health.transit.utils.epix.services;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.2.3
 * 2026-10-07T14:46:59.262+02:00
 * Generated source version: 4.2.3
 */

@WebFault(name = "MPIException", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/")
public class MPIException_Exception extends Exception {

    private MPIException faultInfo;

    public MPIException_Exception() {
        super();
    }

    public MPIException_Exception(String message) {
        super(message);
    }

    public MPIException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public MPIException_Exception(String message, MPIException mpiException) {
        super(message);
        this.faultInfo = mpiException;
    }

    public MPIException_Exception(String message, MPIException mpiException, Throwable cause) {
        super(message, cause);
        this.faultInfo = mpiException;
    }

    public MPIException getFaultInfo() {
        return this.faultInfo;
    }
}
