
package de.fraunhofer.isst.health.transit.utils.epix.services;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.2.3
 * 2026-10-07T14:46:58.595+02:00
 * Generated source version: 4.2.3
 */

@WebFault(name = "ObjectInUseException", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/")
public class ObjectInUseException_Exception extends Exception {

    private ObjectInUseException faultInfo;

    public ObjectInUseException_Exception() {
        super();
    }

    public ObjectInUseException_Exception(String message) {
        super(message);
    }

    public ObjectInUseException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ObjectInUseException_Exception(String message, ObjectInUseException objectInUseException) {
        super(message);
        this.faultInfo = objectInUseException;
    }

    public ObjectInUseException_Exception(String message, ObjectInUseException objectInUseException, Throwable cause) {
        super(message, cause);
        this.faultInfo = objectInUseException;
    }

    public ObjectInUseException getFaultInfo() {
        return this.faultInfo;
    }
}
