
package de.fraunhofer.isst.health.transit.utils.epix.services;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.2.3
 * 2026-10-07T14:46:59.255+02:00
 * Generated source version: 4.2.3
 */

@WebFault(name = "UnknownObjectException", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/")
public class UnknownObjectException_Exception extends Exception {

    private UnknownObjectException faultInfo;

    public UnknownObjectException_Exception() {
        super();
    }

    public UnknownObjectException_Exception(String message) {
        super(message);
    }

    public UnknownObjectException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownObjectException_Exception(String message, UnknownObjectException unknownObjectException) {
        super(message);
        this.faultInfo = unknownObjectException;
    }

    public UnknownObjectException_Exception(String message, UnknownObjectException unknownObjectException, Throwable cause) {
        super(message, cause);
        this.faultInfo = unknownObjectException;
    }

    public UnknownObjectException getFaultInfo() {
        return this.faultInfo;
    }
}
