
package de.fraunhofer.isst.health.transit.utils.epix.services;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.2.3
 * 2026-10-07T14:46:59.270+02:00
 * Generated source version: 4.2.3
 */

@WebFault(name = "ValidatorException", targetNamespace = "http://service.epix.ttp.icmvc.emau.org/")
public class ValidatorException_Exception extends Exception {

    private ValidatorException faultInfo;

    public ValidatorException_Exception() {
        super();
    }

    public ValidatorException_Exception(String message) {
        super(message);
    }

    public ValidatorException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ValidatorException_Exception(String message, ValidatorException validatorException) {
        super(message);
        this.faultInfo = validatorException;
    }

    public ValidatorException_Exception(String message, ValidatorException validatorException, Throwable cause) {
        super(message, cause);
        this.faultInfo = validatorException;
    }

    public ValidatorException getFaultInfo() {
        return this.faultInfo;
    }
}
