services:
  db:
    image: postgres:17
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U liquibase_user -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      TZ: Europe/Berlin
      POSTGRES_PASSWORD_FILE: /run/secrets/db_liquibase.password
      POSTGRES_USER: liquibase_user
      POSTGRES_DB: postgres
    networks:
      - db
      - dms-fhir-backend
      - dic-fhir-backend
      - hrp-fhir-backend
      - dms-bpe-backend
      - dic-bpe-backend
      - hrp-bpe-backend
    secrets:
      - db_liquibase.password
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql
      - type: bind
        source: ./init-db.sh
        target: /docker-entrypoint-initdb.d/init-db.sh
        read_only: true