package de.fraunhofer.isst.health.transit.utils.gpas.psn;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-28T08:40:31.767Z
 * Generated source version: 4.1.1
 */

@WebFault(name = "DBException", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/")
public class DBException extends Exception {

    private de.fraunhofer.isst.health.transit.utils.gpas.psn.DBExceptionType faultInfo;

    public DBException() {
        super();
    }

    public DBException(String message) {
        super(message);
    }

    public DBException(String message, Throwable cause) {
        super(message, cause);
    }

    public DBException(String message, de.fraunhofer.isst.health.transit.utils.gpas.psn.DBExceptionType dbException) {
        super(message);
        this.faultInfo = dbException;
    }

    public DBException(String message, de.fraunhofer.isst.health.transit.utils.gpas.psn.DBExceptionType dbException,
                       Throwable cause) {
        super(message, cause);
        this.faultInfo = dbException;
    }

    public de.fraunhofer.isst.health.transit.utils.gpas.psn.DBExceptionType getFaultInfo() {
        return this.faultInfo;
    }
}
