package de.fraunhofer.isst.health.transit.utils.gpas.psn;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-28T08:40:31.658Z
 * Generated source version: 4.1.1
 */

@WebFault(name = "DeletionForbiddenException", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/")
public class DeletionForbiddenExceptionException extends Exception {

    private de.fraunhofer.isst.health.transit.utils.gpas.psn.DeletionForbiddenException faultInfo;

    public DeletionForbiddenExceptionException() {
        super();
    }

    public DeletionForbiddenExceptionException(String message) {
        super(message);
    }

    public DeletionForbiddenExceptionException(String message, Throwable cause) {
        super(message, cause);
    }

    public DeletionForbiddenExceptionException(String message,
                                               DeletionForbiddenException deletionForbiddenException) {
        super(message);
        this.faultInfo = deletionForbiddenException;
    }

    public DeletionForbiddenExceptionException(String message,
                                               DeletionForbiddenException deletionForbiddenException,
                                               Throwable cause) {
        super(message, cause);
        this.faultInfo = deletionForbiddenException;
    }

    public de.fraunhofer.isst.health.transit.utils.gpas.psn.DeletionForbiddenException getFaultInfo() {
        return this.faultInfo;
    }
}
