package de.fraunhofer.isst.health.transit.utils.gpas.psn;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-28T08:40:31.751Z
 * Generated source version: 4.1.1
 */

@WebFault(name = "DomainIsFullException", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/")
public class DomainIsFullExceptionException extends Exception {

    private de.fraunhofer.isst.health.transit.utils.gpas.psn.DomainIsFullException faultInfo;

    public DomainIsFullExceptionException() {
        super();
    }

    public DomainIsFullExceptionException(String message) {
        super(message);
    }

    public DomainIsFullExceptionException(String message, Throwable cause) {
        super(message, cause);
    }

    public DomainIsFullExceptionException(String message,
                                          DomainIsFullException domainIsFullException) {
        super(message);
        this.faultInfo = domainIsFullException;
    }

    public DomainIsFullExceptionException(String message,
                                          DomainIsFullException domainIsFullException,
                                          Throwable cause) {
        super(message, cause);
        this.faultInfo = domainIsFullException;
    }

    public de.fraunhofer.isst.health.transit.utils.gpas.psn.DomainIsFullException getFaultInfo() {
        return this.faultInfo;
    }
}
