package de.fraunhofer.isst.health.transit.utils.gpas.psn;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-28T08:40:31.786Z
 * Generated source version: 4.1.1
 */

@WebFault(name = "InsertPairException", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/")
public class InsertPairExceptionException extends Exception {

    private de.fraunhofer.isst.health.transit.utils.gpas.psn.InsertPairException faultInfo;

    public InsertPairExceptionException() {
        super();
    }

    public InsertPairExceptionException(String message) {
        super(message);
    }

    public InsertPairExceptionException(String message, Throwable cause) {
        super(message, cause);
    }

    public InsertPairExceptionException(String message,
                                        InsertPairException insertPairException) {
        super(message);
        this.faultInfo = insertPairException;
    }

    public InsertPairExceptionException(String message,
                                        InsertPairException insertPairException,
                                        Throwable cause) {
        super(message, cause);
        this.faultInfo = insertPairException;
    }

    public de.fraunhofer.isst.health.transit.utils.gpas.psn.InsertPairException getFaultInfo() {
        return this.faultInfo;
    }
}
