package de.fraunhofer.isst.health.transit.utils.gpas.psn;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-28T08:40:31.714Z
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidPSNException", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/")
public class InvalidPSNException extends Exception {

    private de.fraunhofer.isst.health.transit.utils.gpas.psn.InvalidPSNExceptionType faultInfo;

    public InvalidPSNException() {
        super();
    }

    public InvalidPSNException(String message) {
        super(message);
    }

    public InvalidPSNException(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidPSNException(String message,
                               de.fraunhofer.isst.health.transit.utils.gpas.psn.InvalidPSNExceptionType invalidPSNException) {
        super(message);
        this.faultInfo = invalidPSNException;
    }

    public InvalidPSNException(String message,
                               de.fraunhofer.isst.health.transit.utils.gpas.psn.InvalidPSNExceptionType invalidPSNException,
                               Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidPSNException;
    }

    public de.fraunhofer.isst.health.transit.utils.gpas.psn.InvalidPSNExceptionType getFaultInfo() {
        return this.faultInfo;
    }
}
