package de.fraunhofer.isst.health.transit.utils.gpas.psn;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-28T08:40:31.619Z
 * Generated source version: 4.1.1
 */

@WebFault(name = "InvalidParameterException", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/")
public class InvalidParameterExceptionException extends Exception {

    private de.fraunhofer.isst.health.transit.utils.gpas.psn.InvalidParameterException faultInfo;

    public InvalidParameterExceptionException() {
        super();
    }

    public InvalidParameterExceptionException(String message) {
        super(message);
    }

    public InvalidParameterExceptionException(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidParameterExceptionException(String message,
                                              InvalidParameterException invalidParameterException) {
        super(message);
        this.faultInfo = invalidParameterException;
    }

    public InvalidParameterExceptionException(String message,
                                              InvalidParameterException invalidParameterException,
                                              Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidParameterException;
    }

    public de.fraunhofer.isst.health.transit.utils.gpas.psn.InvalidParameterException getFaultInfo() {
        return this.faultInfo;
    }
}
