package de.fraunhofer.isst.health.transit.utils.gpas.psn;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-28T08:40:31.796Z
 * Generated source version: 4.1.1
 */
@WebService(targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/", name = "PSNManager")
@XmlSeeAlso({ObjectFactory.class})
public interface PSNManager {

    @WebMethod
    @RequestWrapper(localName = "getPSNNetFor", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetPSNNetFor")
    @ResponseWrapper(localName = "getPSNNetForResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetPSNNetForResponse")
    @WebResult(name = "psnNet", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.psn.PsnNetDTO getPSNNetFor(

            @WebParam(name = "valueOrPSN", targetNamespace = "")
            String valueOrPSN
    ) throws InvalidParameterExceptionException;

    @WebMethod
    @RequestWrapper(localName = "deletePseudonyms", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.DeletePseudonyms")
    @ResponseWrapper(localName = "deletePseudonymsResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.DeletePseudonymsResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.psn.DeletePseudonymsResponse.Return deletePseudonyms(

            @WebParam(name = "psns", targetNamespace = "")
            java.util.List<String> psns,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, InvalidParameterExceptionException, DeletionForbiddenExceptionException;

    @WebMethod
    @RequestWrapper(localName = "deleteAllEntriesForValue", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.DeleteAllEntriesForValue")
    @ResponseWrapper(localName = "deleteAllEntriesForValueResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.DeleteAllEntriesForValueResponse")
    void deleteAllEntriesForValue(

            @WebParam(name = "value", targetNamespace = "")
            String value,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, UnknownValueException, InvalidParameterExceptionException,
            DeletionForbiddenExceptionException;

    @WebMethod
    @RequestWrapper(localName = "getValueFor", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetValueFor")
    @ResponseWrapper(localName = "getValueForResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetValueForResponse")
    @WebResult(name = "value", targetNamespace = "")
    String getValueFor(

            @WebParam(name = "psn", targetNamespace = "")
            String psn,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws PSNNotFoundException, UnknownDomainException, InvalidParameterExceptionException, InvalidPSNException,
            ValueIsAnonymisedExceptionException;

    @WebMethod
    @RequestWrapper(localName = "getOrCreatePseudonymsForList", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetOrCreatePseudonymsForList")
    @ResponseWrapper(localName = "getOrCreatePseudonymsForListResponse",
            targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetOrCreatePseudonymsForListResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.psn.MultiPsnMap getOrCreatePseudonymsForList(

            @WebParam(name = "values", targetNamespace = "")
            java.util.List<String> values,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName,
            @WebParam(name = "minNumber", targetNamespace = "")
            int minNumber
    ) throws UnknownDomainException, InvalidParameterExceptionException, DomainIsFullExceptionException;

    @WebMethod
    @RequestWrapper(localName = "deleteEntries", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.DeleteEntries")
    @ResponseWrapper(localName = "deleteEntriesResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.DeleteEntriesResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.psn.DeleteEntriesResponse.Return deleteEntries(

            @WebParam(name = "values", targetNamespace = "")
            java.util.List<String> values,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, InvalidParameterExceptionException, DeletionForbiddenExceptionException;

    @WebMethod
    @RequestWrapper(localName = "getPSNTreeForPSN", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetPSNTreeForPSN")
    @ResponseWrapper(localName = "getPSNTreeForPSNResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetPSNTreeForPSNResponse")
    @WebResult(name = "psnTree", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.psn.PsnTreeDTO getPSNTreeForPSN(

            @WebParam(name = "psn", targetNamespace = "")
            String psn,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws PSNNotFoundException, UnknownDomainException, InvalidParameterExceptionException, InvalidPSNException,
            ValueIsAnonymisedExceptionException;

    @WebMethod
    @RequestWrapper(localName = "anonymiseEntry", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.AnonymiseEntry")
    @ResponseWrapper(localName = "anonymiseEntryResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.AnonymiseEntryResponse")
    void anonymiseEntry(

            @WebParam(name = "value", targetNamespace = "")
            String value,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, UnknownValueException, DBException, InvalidParameterExceptionException,
            ValueIsAnonymisedExceptionException;

    @WebMethod
    @RequestWrapper(localName = "createPseudonymsForList", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.CreatePseudonymsForList")
    @ResponseWrapper(localName = "createPseudonymsForListResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.CreatePseudonymsForListResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.psn.MultiPsnMap createPseudonymsForList(

            @WebParam(name = "values", targetNamespace = "")
            java.util.List<String> values,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName,
            @WebParam(name = "number", targetNamespace = "")
            int number
    ) throws UnknownDomainException, InvalidParameterExceptionException, DomainIsFullExceptionException;

    @WebMethod
    @RequestWrapper(localName = "deleteAllEntriesForValues", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.DeleteAllEntriesForValues")
    @ResponseWrapper(localName = "deleteAllEntriesForValuesResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.DeleteAllEntriesForValuesResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.psn.DeleteAllEntriesForValuesResponse.Return deleteAllEntriesForValues(

            @WebParam(name = "values", targetNamespace = "")
            java.util.List<String> values,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, InvalidParameterExceptionException, DeletionForbiddenExceptionException;

    @WebMethod
    @RequestWrapper(localName = "createPseudonymFor", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.CreatePseudonymFor")
    @ResponseWrapper(localName = "createPseudonymForResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.CreatePseudonymForResponse")
    @WebResult(name = "psn", targetNamespace = "")
    String createPseudonymFor(

            @WebParam(name = "value", targetNamespace = "")
            String value,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, InvalidParameterExceptionException, DomainIsFullExceptionException;

    @WebMethod
    @RequestWrapper(localName = "isAnonymised", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.IsAnonymised")
    @ResponseWrapper(localName = "isAnonymisedResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.IsAnonymisedResponse")
    @WebResult(name = "return", targetNamespace = "")
    boolean isAnonymised(

            @WebParam(name = "psn", targetNamespace = "")
            String psn,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, PSNNotFoundException, InvalidParameterExceptionException, InvalidPSNException;

    @WebMethod
    @RequestWrapper(localName = "getValueForList", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetValueForList")
    @ResponseWrapper(localName = "getValueForListResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetValueForListResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.psn.GetValueForListResponse.Return getValueForList(

            @WebParam(name = "psnList", targetNamespace = "")
            java.util.List<String> psnList,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, InvalidParameterExceptionException;

    @WebMethod
    @RequestWrapper(localName = "getPseudonymsForList", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetPseudonymsForList")
    @ResponseWrapper(localName = "getPseudonymsForListResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetPseudonymsForListResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.psn.MultiPsnMap getPseudonymsForList(

            @WebParam(name = "values", targetNamespace = "")
            java.util.List<String> values,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, InvalidParameterExceptionException;

    @WebMethod
    @RequestWrapper(localName = "anonymisePseudonym", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.AnonymisePseudonym")
    @ResponseWrapper(localName = "anonymisePseudonymResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.AnonymisePseudonymResponse")
    void anonymisePseudonym(

            @WebParam(name = "psn", targetNamespace = "")
            String psn,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, PSNNotFoundException, DBException, InvalidParameterExceptionException, InvalidPSNException;

    @WebMethod
    @RequestWrapper(localName = "anonymiseEntries", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.AnonymiseEntries")
    @ResponseWrapper(localName = "anonymiseEntriesResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.AnonymiseEntriesResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.psn.AnonymiseEntriesResponse.Return anonymiseEntries(

            @WebParam(name = "values", targetNamespace = "")
            java.util.List<String> values,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, DBException, InvalidParameterExceptionException;

    @WebMethod
    @RequestWrapper(localName = "getOrCreatePseudonymFor", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetOrCreatePseudonymFor")
    @ResponseWrapper(localName = "getOrCreatePseudonymForResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetOrCreatePseudonymForResponse")
    @WebResult(name = "psn", targetNamespace = "")
    String getOrCreatePseudonymFor(

            @WebParam(name = "value", targetNamespace = "")
            String value,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, InvalidParameterExceptionException, DomainIsFullExceptionException;

    @WebMethod
    @RequestWrapper(localName = "isAnonym", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.IsAnonym")
    @ResponseWrapper(localName = "isAnonymResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.IsAnonymResponse")
    @WebResult(name = "return", targetNamespace = "")
    boolean isAnonym(

            @WebParam(name = "value", targetNamespace = "")
            String value
    ) throws InvalidParameterExceptionException;

    @WebMethod
    @RequestWrapper(localName = "getPseudonymForValuePrefix", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetPseudonymForValuePrefix")
    @ResponseWrapper(localName = "getPseudonymForValuePrefixResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetPseudonymForValuePrefixResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.psn.GetPseudonymForValuePrefixResponse.Return getPseudonymForValuePrefix(

            @WebParam(name = "valuePrefix", targetNamespace = "")
            String valuePrefix,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, InvalidParameterExceptionException;

    @WebMethod
    @RequestWrapper(localName = "getPseudonymFor", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetPseudonymFor")
    @ResponseWrapper(localName = "getPseudonymForResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetPseudonymForResponse")
    @WebResult(name = "psn", targetNamespace = "")
    String getPseudonymFor(

            @WebParam(name = "value", targetNamespace = "")
            String value,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, UnknownValueException, InvalidParameterExceptionException;

    @WebMethod
    @RequestWrapper(localName = "anonymisePseudonyms", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.AnonymisePseudonyms")
    @ResponseWrapper(localName = "anonymisePseudonymsResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.AnonymisePseudonymsResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.psn.AnonymisePseudonymsResponse.Return anonymisePseudonyms(

            @WebParam(name = "psns", targetNamespace = "")
            java.util.List<String> psns,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, DBException, InvalidParameterExceptionException;

    @WebMethod
    @RequestWrapper(localName = "getPseudonymsForValuePrefix", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetPseudonymsForValuePrefix")
    @ResponseWrapper(localName = "getPseudonymsForValuePrefixResponse",
            targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetPseudonymsForValuePrefixResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.psn.MultiPsnMap getPseudonymsForValuePrefix(

            @WebParam(name = "valuePrefix", targetNamespace = "")
            String valuePrefix,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, InvalidParameterExceptionException;

    @WebMethod
    @RequestWrapper(localName = "insertValuePseudonymPairs",
            targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.InsertValuePseudonymPairs")
    @ResponseWrapper(localName = "insertValuePseudonymPairsResponse",
            targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.InsertValuePseudonymPairsResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.psn.InsertValuePseudonymPairsResponse.Return insertValuePseudonymPairs(

            @WebParam(name = "pairs", targetNamespace = "")
            de.fraunhofer.isst.health.transit.utils.gpas.psn.MultiPsnList pairs,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, InvalidParameterExceptionException;

    @WebMethod
    @RequestWrapper(localName = "getPseudonymsFor", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetPseudonymsFor")
    @ResponseWrapper(localName = "getPseudonymsForResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetPseudonymsForResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.psn.GetPseudonymsForResponse.Return getPseudonymsFor(

            @WebParam(name = "value", targetNamespace = "")
            String value,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, UnknownValueException, InvalidParameterExceptionException;

    @WebMethod
    @RequestWrapper(localName = "getOrCreatePseudonymForList", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetOrCreatePseudonymForList")
    @ResponseWrapper(localName = "getOrCreatePseudonymForListResponse",
            targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetOrCreatePseudonymForListResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.psn.GetOrCreatePseudonymForListResponse.Return getOrCreatePseudonymForList(

            @WebParam(name = "values", targetNamespace = "")
            java.util.List<String> values,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, InvalidParameterExceptionException, DomainIsFullExceptionException;

    @WebMethod
    @RequestWrapper(localName = "getPseudonymForList", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetPseudonymForList")
    @ResponseWrapper(localName = "getPseudonymForListResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetPseudonymForListResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.psn.GetPseudonymForListResponse.Return getPseudonymForList(

            @WebParam(name = "values", targetNamespace = "")
            java.util.List<String> values,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, InvalidParameterExceptionException;

    @WebMethod
    @RequestWrapper(localName = "insertValuePseudonymPair", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.InsertValuePseudonymPair")
    @ResponseWrapper(localName = "insertValuePseudonymPairResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.InsertValuePseudonymPairResponse")
    void insertValuePseudonymPair(

            @WebParam(name = "value", targetNamespace = "")
            String value,
            @WebParam(name = "pseudonym", targetNamespace = "")
            String pseudonym,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws InsertPairExceptionException, UnknownDomainException, InvalidParameterExceptionException;

    @WebMethod
    @RequestWrapper(localName = "createPseudonymsFor", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.CreatePseudonymsFor")
    @ResponseWrapper(localName = "createPseudonymsForResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.CreatePseudonymsForResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.psn.CreatePseudonymsForResponse.Return createPseudonymsFor(

            @WebParam(name = "value", targetNamespace = "")
            String value,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName,
            @WebParam(name = "number", targetNamespace = "")
            int number
    ) throws UnknownDomainException, InvalidParameterExceptionException, DomainIsFullExceptionException;

    @WebMethod
    @RequestWrapper(localName = "validatePSN", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.ValidatePSN")
    @ResponseWrapper(localName = "validatePSNResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.ValidatePSNResponse")
    void validatePSN(

            @WebParam(name = "psn", targetNamespace = "")
            String psn,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, InvalidParameterExceptionException, InvalidPSNException;

    @WebMethod
    @RequestWrapper(localName = "deleteEntry", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.DeleteEntry")
    @ResponseWrapper(localName = "deleteEntryResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.DeleteEntryResponse")
    void deleteEntry(

            @WebParam(name = "value", targetNamespace = "")
            String value,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, UnknownValueException, InvalidParameterExceptionException,
            DeletionForbiddenExceptionException;

    @WebMethod
    @RequestWrapper(localName = "anonymiseAllEntriesForValue", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.AnonymiseAllEntriesForValue")
    @ResponseWrapper(localName = "anonymiseAllEntriesForValueResponse",
            targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.AnonymiseAllEntriesForValueResponse")
    void anonymiseAllEntriesForValue(

            @WebParam(name = "value", targetNamespace = "")
            String value,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, UnknownValueException, DBException, InvalidParameterExceptionException,
            ValueIsAnonymisedExceptionException;

    @WebMethod
    @RequestWrapper(localName = "deletePseudonym", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.DeletePseudonym")
    @ResponseWrapper(localName = "deletePseudonymResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.DeletePseudonymResponse")
    void deletePseudonym(

            @WebParam(name = "psn", targetNamespace = "")
            String psn,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws InvalidParameterExceptionException, InvalidPSNException, UnknownDomainException, UnknownValueException,
            PSNNotFoundException, DeletionForbiddenExceptionException;

    @WebMethod
    @RequestWrapper(localName = "anonymiseAllEntriesForValues", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.AnonymiseAllEntriesForValues")
    @ResponseWrapper(localName = "anonymiseAllEntriesForValuesResponse",
            targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.AnonymiseAllEntriesForValuesResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.psn.AnonymiseAllEntriesForValuesResponse.Return anonymiseAllEntriesForValues(

            @WebParam(name = "values", targetNamespace = "")
            java.util.List<String> values,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, DBException, InvalidParameterExceptionException;

    @WebMethod
    @RequestWrapper(localName = "getOrCreatePseudonymsFor", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetOrCreatePseudonymsFor")
    @ResponseWrapper(localName = "getOrCreatePseudonymsForResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.GetOrCreatePseudonymsForResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.psn.GetOrCreatePseudonymsForResponse.Return getOrCreatePseudonymsFor(

            @WebParam(name = "value", targetNamespace = "")
            String value,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName,
            @WebParam(name = "minNumber", targetNamespace = "")
            int minNumber
    ) throws UnknownDomainException, InvalidParameterExceptionException, DomainIsFullExceptionException;

    @WebMethod
    @RequestWrapper(localName = "createPseudonymForList", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.CreatePseudonymForList")
    @ResponseWrapper(localName = "createPseudonymForListResponse", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/",
            className = "de.fraunhofer.isst.health.transit.utils.gpas.psn.CreatePseudonymForListResponse")
    @WebResult(name = "return", targetNamespace = "")
    de.fraunhofer.isst.health.transit.utils.gpas.psn.CreatePseudonymForListResponse.Return createPseudonymForList(

            @WebParam(name = "values", targetNamespace = "")
            java.util.List<String> values,
            @WebParam(name = "domainName", targetNamespace = "")
            String domainName
    ) throws UnknownDomainException, InvalidParameterExceptionException, DomainIsFullExceptionException;
}
