package de.fraunhofer.isst.health.transit.utils.gpas.psn;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;

/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-28T08:40:31.848Z
 * Generated source version: 4.1.1
 */
@WebServiceClient(name = "PSNManagerBeanService",
        wsdlLocation = "http://gpas.develop-dmu.dmu.dev.num-rdp.de/gpas/gpasService?wsdl",
        targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/")
public class PSNManagerBeanService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://psn.ttp.ganimed.icmvc.emau.org/", "PSNManagerBeanService");
    public static final QName GPAS_SERVICE_PORT = new QName("http://psn.ttp.ganimed.icmvc.emau.org/", "gpasServicePort");

    static {
        URL url = null;
        try {
            url = URI.create("http://gpas.develop-dmu.dmu.dev.num-rdp.de/gpas/gpasService?wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PSNManagerBeanService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}",
                            "http://gpas.develop-dmu.dmu.dev.num-rdp.de/gpas/gpasService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PSNManagerBeanService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PSNManagerBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PSNManagerBeanService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PSNManagerBeanService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PSNManagerBeanService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PSNManagerBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }


    /**
     * @return returns PSNManager
     */
    @WebEndpoint(name = "gpasServicePort")
    public PSNManager getGpasServicePort() {
        return super.getPort(GPAS_SERVICE_PORT, PSNManager.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in
     *                 the <code>features</code> parameter will have their default values.
     * @return returns PSNManager
     */
    @WebEndpoint(name = "gpasServicePort")
    public PSNManager getGpasServicePort(WebServiceFeature... features) {
        return super.getPort(GPAS_SERVICE_PORT, PSNManager.class, features);
    }

}
