package de.fraunhofer.isst.health.transit.utils.gpas.psn;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-28T08:40:31.709Z
 * Generated source version: 4.1.1
 */

@WebFault(name = "PSNNotFoundException", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/")
public class PSNNotFoundException extends Exception {

    private de.fraunhofer.isst.health.transit.utils.gpas.psn.PSNNotFoundExceptionType faultInfo;

    public PSNNotFoundException() {
        super();
    }

    public PSNNotFoundException(String message) {
        super(message);
    }

    public PSNNotFoundException(String message, Throwable cause) {
        super(message, cause);
    }

    public PSNNotFoundException(String message,
                                de.fraunhofer.isst.health.transit.utils.gpas.psn.PSNNotFoundExceptionType psnNotFoundException) {
        super(message);
        this.faultInfo = psnNotFoundException;
    }

    public PSNNotFoundException(String message,
                                de.fraunhofer.isst.health.transit.utils.gpas.psn.PSNNotFoundExceptionType psnNotFoundException,
                                Throwable cause) {
        super(message, cause);
        this.faultInfo = psnNotFoundException;
    }

    public de.fraunhofer.isst.health.transit.utils.gpas.psn.PSNNotFoundExceptionType getFaultInfo() {
        return this.faultInfo;
    }
}
