package de.fraunhofer.isst.health.transit.utils.gpas.psn;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-28T08:40:31.643Z
 * Generated source version: 4.1.1
 */

@WebFault(name = "UnknownDomainException", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/")
public class UnknownDomainException extends Exception {

    private de.fraunhofer.isst.health.transit.utils.gpas.psn.UnknownDomainExceptionType faultInfo;

    public UnknownDomainException() {
        super();
    }

    public UnknownDomainException(String message) {
        super(message);
    }

    public UnknownDomainException(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownDomainException(String message,
                                  UnknownDomainExceptionType unknownDomainException) {
        super(message);
        this.faultInfo = unknownDomainException;
    }

    public UnknownDomainException(String message,
                                  UnknownDomainExceptionType unknownDomainException,
                                  Throwable cause) {
        super(message, cause);
        this.faultInfo = unknownDomainException;
    }

    public de.fraunhofer.isst.health.transit.utils.gpas.psn.UnknownDomainExceptionType getFaultInfo() {
        return this.faultInfo;
    }
}
