package de.fraunhofer.isst.health.transit.utils.gpas.psn;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-28T08:40:31.692Z
 * Generated source version: 4.1.1
 */

@WebFault(name = "UnknownValueException", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/")
public class UnknownValueException extends Exception {

    private de.fraunhofer.isst.health.transit.utils.gpas.psn.UnknownValueExceptionType faultInfo;

    public UnknownValueException() {
        super();
    }

    public UnknownValueException(String message) {
        super(message);
    }

    public UnknownValueException(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownValueException(String message,
                                 UnknownValueExceptionType unknownValueException) {
        super(message);
        this.faultInfo = unknownValueException;
    }

    public UnknownValueException(String message,
                                 UnknownValueExceptionType unknownValueException,
                                 Throwable cause) {
        super(message, cause);
        this.faultInfo = unknownValueException;
    }

    public de.fraunhofer.isst.health.transit.utils.gpas.psn.UnknownValueExceptionType getFaultInfo() {
        return this.faultInfo;
    }
}
