package de.fraunhofer.isst.health.transit.utils.gpas.psn;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.1
 * 2025-03-28T08:40:31.743Z
 * Generated source version: 4.1.1
 */

@WebFault(name = "ValueIsAnonymisedException", targetNamespace = "http://psn.ttp.ganimed.icmvc.emau.org/")
public class ValueIsAnonymisedExceptionException extends Exception {

    private de.fraunhofer.isst.health.transit.utils.gpas.psn.ValueIsAnonymisedException faultInfo;

    public ValueIsAnonymisedExceptionException() {
        super();
    }

    public ValueIsAnonymisedExceptionException(String message) {
        super(message);
    }

    public ValueIsAnonymisedExceptionException(String message, Throwable cause) {
        super(message, cause);
    }

    public ValueIsAnonymisedExceptionException(String message,
                                               ValueIsAnonymisedException valueIsAnonymisedException) {
        super(message);
        this.faultInfo = valueIsAnonymisedException;
    }

    public ValueIsAnonymisedExceptionException(String message,
                                               ValueIsAnonymisedException valueIsAnonymisedException,
                                               Throwable cause) {
        super(message, cause);
        this.faultInfo = valueIsAnonymisedException;
    }

    public de.fraunhofer.isst.health.transit.utils.gpas.psn.ValueIsAnonymisedException getFaultInfo() {
        return this.faultInfo;
    }
}
